homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 20
  unit_system: imperial
  time_zone: America/New_York  
  customize:  !include customize.yaml
  
  # customize_glob:
  #   light.*:
  #     custom_ui_state_card: state-card-custom-ui
  
config:
updater:
  reporting: no

frontend: !include includes/frontend.yaml

customizer:
  custom_ui: local

discovery:
  ignore:
    - plex_mediaserver
    #- harmony
    - roku
    - sabnzbd
    - philips_hue
    - deconz
conversation:

ifttt:
  key: !secret ifttt_api
sun:
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  # - platform: voicerss
  #   api_key: !secret voicerss_key
  # - platform: amazon_polly
  #   aws_access_key_id: !secret aws_key
  #   aws_secret_access_key: !secret aws_secret_key
  #   name: polly
  #   # English US Female
  #   voice: Salli
  #   # English UK Female
  #   # voice: Amy
alexa: 
  flash_briefings:
    whoishome:
      - title: Who's at home?
        text: >
          {%- if is_state('device_tracker.vicky_phone', 'home') and
                 is_state('device_tracker.lechu_phone', 'home') -%}
            You are both home, you silly
          {%- else -%}
            Lekshmi is at {{ states("device_tracker.lechu_phone") }}
            and Vicky is at {{ states("device_tracker.vicky_phone") }}
          {% endif %}
  smart_home:
    filter:
      include_domains:
        - alert
        - automation
        - cover
        - fan
        - input_boolean
        - media_player
        - scene
        - script
        - switch
#  intents: !include_dir_merge_named alexa
dialogflow:
intent_script: !include includes/intent_script.yaml
panel_iframe:
  nodered_flows:
    title: 'Node-RED Flows'
    url: !secret nodered_url
    icon: mdi:nodejs
  # shinobi:
    # title: Shinobi
    # icon: mdi:cctv
    # url: http://192.168.1.200:5000
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
  - name: tiles
    sidebar_title: Tiles
    sidebar_icon: mdi:view-dashboard
    url_path: tiles
    config: !include includes/tiles.yaml
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: smartthings


###########################################################
#
# Includes
#
############################################################

# Single Files
history: #!include includes/history.yaml
recorder: !include includes/recorder.yaml
logbook: #!include includes/logbook.yaml
logger: #!include includes/logger.yaml

zone: !include includes/zones.yaml
#cloud: !include includes/cloud.yaml
http: !include includes/http.yaml
switch: !include includes/switches.yaml
remote: !include includes/remote.yaml
binary_sensor: !include includes/binary_sensors.yaml
notify: !include includes/notify.yaml
camera: !include includes/cameras.yaml
shell_command: !include includes/shell_command.yaml
hue: !include includes/philips_hue.yaml
weblink: !include includes/weblink.yaml
# sabnzbd: !include includes/sabnzbd.yaml
# light: !include includes/light.yaml
media_player: !include includes/media_players.yaml
device_tracker: !include includes/device_tracker.yaml
automation: !include automations.yaml
scene: !include includes/scenes.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
rest_command: !include includes/rest.yaml

# Group Merge Directory
sensor: !include_dir_merge_list sensors/
script: !include_dir_merge_named scripts
group: !include_dir_merge_named group/
input_select: !include_dir_merge_named input_select
automation old: !include_dir_merge_list automations


