############################################################
#
# Home Assistant Sensors: Speed Test
#
############################################################

- platform: speedtest
  name: Internet Speed Test
  monitored_conditions:
    - ping
    - download
    - upload
  minute:
    - 0