############################################################
#
# Home Assistant Sensors: System
#
############################################################
- platform: cpuspeed
- platform: systemmonitor
  resources:
    - type: disk_use
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: uptime
  unit_of_measurement: minutes
- platform: template
  sensors:
    hassuptime:
      friendly_name: "HASS Uptime"
      value_template: >-
        {% set uptime = states.sensor.uptime.state | round %}
        {% set minutes = (uptime % 60) | int %}
        {% set hours = ((uptime / 60) % 24) | int %}
        {% set days = (uptime / 1440) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 day
          {%- else -%}
            {{ days }} days
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {{ '%02d' % hours }}:{{ '%02d' % minutes }} hrs