############################################################
#
# Home Assistant Media Players
#
############################################################

# - platform: plex
  # include_non_clients: true
  # use_episode_art: true
- platform: firetv
  host: !secret aftv_ip
  name: Amazon FireTV

- platform: kodi
  host: !secret node_computer_ip
  port: 8080
  username: !secret kodi_usr
  password: !secret kodi_pwd

- platform: mpd
  name: mpd
  host: !secret ha_ip
  port: 6600

- platform: cast
  host: !secret cast_googleMini_1
- platform: cast
  host: !secret cast_googleMini_2