###########################################################
#
# Home Assistant Switches
#
############################################################


###########################################################
# QNAP
############################################################
- platform: wake_on_lan
  mac_address: !secret nas_mac_address

###########################################################
# SONOFF
############################################################
- platform: mqtt
  name: "Sonoff 1"
  command_topic: "cmnd/sonoff001/power"
  state_topic: "stat/sonoff001/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Sonoff 2"
  command_topic: "cmnd/sonoff002/power"
  state_topic: "stat/sonoff002/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true


- platform: mqtt
  name: "Samsung Outlet"
  state_topic: smartthings/Outlet/switch
  command_topic: smartthings/Outlet/switch
  payload_on: "on"
  payload_off: "off"
  retain: true
###########################################################
# ETECK RF Switches
############################################################
- platform: rpi_rf
  gpio: 17
  switches:
   switch01:
     protocol: 1
     pulselength: 187
     code_on: 4543795
     code_off: 4543804
   switch02:
     protocol: 1
     pulselength: 187
     code_on: 4543939
     code_off: 4543948
   switch03:
     protocol: 1
     pulselength: 187
     code_on: 4544259
     code_off: 4544268
   switch04:
     protocol: 1
     pulselength: 188
     code_on: 4545795
     code_off: 4545804
   switch05:
     protocol: 1
     pulselength: 185
     code_on: 333107
     code_off: 333116
   switch06:
     protocol: 1
     pulselength: 186
     code_on: 335107
     code_off: 335116
   switch07:
     protocol: 1
     pulselength: 187
     code_on: 333571
     code_off: 333580
   switch08:
     protocol: 1
     pulselength: 186
     code_on: 341251
     code_off: 341260
   all_switch:
     protocol: 1
     pulselength: 187
     code_on: 4551939
     code_off:


- platform: tplink
  name: "tplink_plug_01"
  host: 192.168.1.3

# - platform: tplink
#   name: "bass"
#   host: 192.168.1.5

###########################################################
# Broadlink RM RF
############################################################
- platform: broadlink
  host: !secret broadlink_ip_address
  mac: !secret broadlink_mac_address
  type: rm_mini
  friendly_name: 'RM Mini'
  timeout: 15
  switches:
    ac_lg:
      friendly_name: "Air Conditioner"
      command_on: 'JgBgAQABLJMVNRU2FRAXDxcPFREWEBczFREXMxU2FREXDxQRGA4VERczFTYVEBURFREXDxQSFw4VERU1FREWDxY1FREWEBcPFg8WDxYQFhAXDhYQFhAXDxcOFhAWDxcPFg8XDxcPFw4YAAEEFw4XDxcOFw8XDxYPFzQXNBcPFw4XDxYPFhAXDxcPFw4XDxcOFw8WDxcPFw8XDxcOFw8XDhcPFw4XDxcPFw8XDhcPFw4XDxcOFw8XDxcPFw8WDxcOFw8XDxYPGA4XDxcPFw4XDxcOFw8XDhcPFw8XDxczFw8XDhcPFzQXDxc0FzMXAAEEFw8WDxYQFRAWEBcPFhAXDhY1Fg8WNRYQFw4WNRURFhAWDxURFBEWEBcPFRAYDhURFRAYDhcOGA4XDxURFBIUNhURFRAYDhc0FDYVNhUSFBEXDhgOFw4YDhURFw8XDxcOFzQUERc0FTYUNxQRFw8XNBQADQUAAAAAAAAAAA=='
      command_off: 'JgBgAQABK5QVNRU2FRAVERURFREVERU1FREVNRU2FREVEBURFREVERU1FTYVERUQFREVERURFREVEBU2FRAVERU2FRAVERURFREUERUQFREVERURFREVEBURFRAVEBURFREVERURFRAVAAEGFRAVERQRFREVEBURFTcVNRURFRAVERUQFREVERURFREVEBUQFREVEBURFREVERURFRAVEBURFREVEBURFREVERUQFRAVERURFRAVERURFREVEBURFRAVERUQFREVERURFRAVERUQFREVERUQFREVERU2FRAVERUQFTYVERU2FTUWAAEGFRAVEBURFREVEBURFREVERU1FREVNRURFREVNhURFREVEBUQFREVEBURFREVERURFRAVEBURFREUERURFREVNhUQFREVEBU2FREVNhURFRAVERUQFRAVERURFREVERUQFTYVEBU2FTUWEBURFREVNRQADQUAAAAAAAAAAA=='
    ac_night_high_1:
      friendly_name: "Sleep High Timer 1H 78F"
      command_on: 'JgBgAQABLZIUNxQ2FBMTEhMTExMTExM3FBIUNhQ3FBITExMTExMTExQ1FDcUEhM3FBMTExMTFBEVEBU2FBIUNhURFDcVERURFBETExQRFBIUERURFREVERQRFBIUERQSFBIUERUSFBETAAEHFREUERURFBIUERURFTYVNhURFBEUEhQRFREVERQSFBIUERQSFBEUEhQSFBEVERURFBEVERQRFREUEhQSFBEVERUQFREUERURFBIUEhQSFBEVERQRFBIUERURFBIUEhQRFREUERURFBEVERURFREVERQ2FREUEhQRFREUNxU2FTUVAAEHFRAVERQRFREUEhQSFBIUERURFDYVERQRFREVERQSFBIUERQRFREUERURFREVERURFBEVERQRFREVERQRFhEVNRYQFBEWEBQ2FjUVNhYRFRAWEBUQFRAWEBURFREUEhUQFhAUNhYQFTUWNRY1FhEVNRQADQUAAAAAAAAAAA=='
    ac_night_high_2:
      friendly_name: "Sleep High Timer 2H"
      command_on: 'JgBgAQABLZIXNBczFw8XDhcPFw8XDxc0Fw4XNBczFw8XDxcPFw8XDhc0FzMXDxY1Fg8YDhYQGA4WDxgzFg8WNRYQFjUVERURFRAVERcOFREUERURGA4VERcOGA4XDhcPFREUERgOFRAYAAEDFREXDhcPFBEYDhURFTYVNhUQFw8XDhURFBEYDhURFw8WDxcPFg8XDxYQFhAUEhQRFhAWDxYPFREWEBYQFhAUERYQFg8WEBUQFREVERYQFREWDxUQFw8VERYPFw8VERURFRAVERUQFREVERYQFREVEBU2FRAVERUQFREVNhU2FTUVAAEGFREVEBYQFRAVERURFREVERUQFTUVERURFRAVERURFREVEBURFRAVERURFREVERUQFREVEBURFRAVERURFREVNhUQFREVEBU2FjUXNBURFREVEBUQFREVERUQFREVERURFRAVNhYPFTYVNhc0FREVNRUADQUAAAAAAAAAAA=='
    ac_night_high_5:
      friendly_name: "Sleep High Timer 5H"
      command_on: 'JgBgAQABLZMUNhU2FBIUERURFREUEhQ2FhAVNRY1FhAVERUQFhEVEBY0FjUWEBY0FhAWEBYQFhAWDxY0Fw8WNRcPFjUWEBYQFg8WEBUQFhAWEBUQFhAWEBYPFhAWDxYQFhAWEBYQFg8WAAEFFw4XDxYQFg8WEBYQFjUXNBcOFhAWDxYQFhAWEBYQFg8WEBYPFhAVEBYQFhAWEBYQFg8WDxYQFhAWDxYQFhAWEBYPFhAVEBYQFhAVEBYQFhAWDxYQFg8WEBYQFRAWEBYQFg8WEBYPFhAWEBYQFhAWDxY0GA4WEBYPFhAWNRc0FzMXAAEEFw4XDxYQFhAWDxYQFhAWEBYPFjUXDxYPFhAWEBYQFhAVEBYPFhAWDxYQFhAWEBYQFg8WDxYQFhAVEBYQFhAWNBgOFhAWDxY1FzMYNBcPFhAWDxYPFhAWEBYPFhAWEBYQFg8WNBgOFjUXNBc0Fw8WNBYADQUAAAAAAAAAAA=='
    ac_night_medium_1:
      friendly_name: "Sleep Medium Timer 1H 75F"
      command_on: 'JgBgAQABLJMVNhU2FBEWEBYQFg8VERc0FREWNBU2FREWDxYQFhAVERY0FTYVEBc0FREWEBYQFg8VERY0FREWNRQ3FDcUNxU2FBEWDxYQFhAUERcPFhAWEBYPFhAUERYQFhAWEBYQFg8VAAEGFRAVERQRFREVERUQFTYVNhURFRAWEBUQFREVERURFRAWEBYPFRAWEBURFREVERUQFREVEBURFRAVERURFREVEBURFRAVERUQFREVERURFREVEBYPFREWDxURFhAVERURFRAWDxURFREVEBYQFREVERU2FRAVERQRFTYVNhURFRAWAAEFFhAUERYPFREWEBURFhAVEBURFTUVERUQFhAWEBYQFREVEBYPFhAVEBURFREWEBYQFRAWDxYQFhAVEBURFREWEBYPFREUERU2FTYWNRURFhAVEBYPFREWEBUQFhEUERURFREUNhYQFTUVNhY1FhAVERQADQUAAAAAAAAAAA=='
    ac_night_medium_2:
      friendly_name: "Sleep Medium Timer 2H"
      command_on: 'JgBgAQABLZMWNRU1FhAVERQRFhAVERU2FREWNBU2FREVERUQFhAVERU2FjQVERU2FhAVERURFRAVERQ2FREVNhY1FTYWNRY1FhAVEBYQFBEVERURFhAVERYPFg8WEBURFhAUERURFREUAAEHFg8WEBYPFhAWEBURFTYWNRYPFREVEBUSFBEVERURFhAVEBUQFREVERQRFhAVEhUQFRAWEBURFRAVERYQFREVERQRFRAWEBYQFRAWEBYQFREVEBYQFRAWEBYQFhAVERQSFBEVEBURFhAWEBURFBIVEBU2Fg8VERYPFjUWNhYQFg8WAAEFFhAUERURFRAVERURFREVERYPFTYWDxYQFREVERURFhAVEBYPFREWEBUQFhAWEBURFRAVERUQFhAWEBYQFREVERUQFRAWEBY1FjUWNRYQFhAWDxYPFhAVERYQFBEWERUQFREVNRYQFjUVNhY1FREVEBUADQUAAAAAAAAAAA=='
    ac_night_medium_5:
      friendly_name: "Sleep Medium Timer 5H"
      command_on: 'JgBgAQABK5QVNhQ2FREVEBURFREVERU2FRAVNhQ2FREVERURFhAVEBU2FTUVERU2FBEXDxYQFREVEBU2FRAWNRU2FTYVNhU2FREVEBUQFREVERURFREVEBURFRAVERUQFREVERURFRAVAAEGFREVEBURFRAVERURFTYVNhQRFRAVERURFRAVERURFREVEBURFRAVERURFREVERUQFREVEBURFRAVERURFREVERUQFRAVERURFRAVERURFREVEBURFRAVERUQFhAVERURFRAVERUQFREVERUQFREVERU1Fw8VEBURFTYVNhcPFRAVAAEGFw4VERUQFREVERURFREVEBURFTUXDxUQFREVERURFRAVERUQFREVEBURFREVERUQFREVEBURFRAVERURFREVERUQFRAVERU2FjUWNRYQFRAVERUQFREVEBURFREVERUQFREVNRcPFTYWNBc0FxAVEBQADQUAAAAAAAAAAA=='
    ac_night_low_1:
      friendly_name: "Sleep Low Timer 1H 70F"
      command_on: 'JgBgAQABLJMWNBU2FRAVERYQFREWEBU1FhAVNRU2FREVERQRFhAVERU1FjUWEBY1FBEVERURFhAWDxU2Fg8VNhYQFTYVERY1FRAWDxURFREWEBUQFhEVEBYQFRAVEBURFREWEBYQFg8VAAEGFg8VERUQFREVERURFjUWNRYPFREVEBURFREUEhUQFREVEBURFRAVERYQFREVERYPFREVEBYQFRAWEBURFREWDxcPFRAWEBURFBEVERYQFREVEBYPFREVERUQFREVERURFRAWEBUQFREVERUQFREVERY0FhAWDxURFhAVNhY1Fg8VAAEGFg8WEBUQFhAVERURFREVEBURFDYWEBYPFREWEBURFhAUERYPFhAVERQRFREVERURFRAVEBURFREVEBURFhAWEBYPFREUERY1FjQWNhYQFg8WEBYPFhAVEBYQFhAVERURFRAWNBYQFTYVNhU2FBIVEBQADQUAAAAAAAAAAA=='
    ac_night_low_2:
      friendly_name: "Sleep Low Timer 2H"
      command_on: 'JgBgAQABLJMVNhU2FBEVERURFBEWERU1FREUNhY1FhAUERURFREVERU1FTYVEBU2FREWEBURFhAVEBU1FREVNhURFTYVERU1FhAVEBURFRAVERURFREVERYPFRAWEBURFRAVERURFRAVAAEHFRAVERQRFREVERQRFTcVNRYQFBEWEBQRFhAVERURFhAUERUQFREVEBURFhAVERURFRAVERQRFREWEBQSFBIUERUQFREVEBURFREVERURFRAVERQRFhAUERURFREVERYPFREVEBYQFBEWEBURFREVERQ2FhAVEBURFREWNRU2Fg8WAAEFFREVEBYQFRAVERURFhAWEBQRFTUVERYQFBEVERYQFhAVEBURFBEVERUQFREVERURFRAVERUQFhAVERYQFBIWDxURFRAVEBY1FTYWNRURFREVEBYPFREWEBQRFREVERURFRAVNhYPFjUVNhU2FhAVEBUADQUAAAAAAAAAAA=='
    ac_night_low_5:
      friendly_name: "Sleep Low Timer 5H"
      command_on: 'JgBgAQABLJMVNRU2FRAVERYQFhAUEhY0FREWNBY1FREVERURFBIVEBY1FTUVERU2FREUERYRFBEWDxU2FhAUNhURFTYVERU2FRAVERYPFREVERYQFBIUERURFRAVEBURFhAVERURFRAVAAEGFRAVERUQFREVERQSFDcVNRURFRAVERYPFREVERURFREVEBUQFREVERQRFREWEBURFRAVERUQFREWDxURFREVERYPFREUERYQFhAUERURFREVEBURFBEVERURFBEVERURFRAWEBUQFhAVERYQFREUERU2FBEWEBUQFhAVNhY1FRAWAAEFFhAVEBYQFBEVERURFREVERQRFjQVERURFRAVERYQFhAVEBURFRAVERURFRAVERURFRAVERUQFhAVERURFREVEBURFBEVEBY1FTYWNRURFREUERURFRAVERUQFREVERYQFRAVNhUQFjUVNhY1FREWDxUADQUAAAAAAAAAAA=='

    
    
    
    fan:
      friendly_name: "Fan"
      command_on: 'JgB6ACoMKwwPKSkNKg0OKQ8oDykNKg4pDygq4yoMKg0PKCoNKg0OKQ8oDygPKQ4pDygq4ioNKgwQJyoNKg0PKA8oDykOKQ8oDygq4yoNKgwPKCoNKg0OKQ8oDygPKQ4pDygq4yoNKgwPKCoNKg0OKQ8oDygPKQ4pDygqAA0FAAAAAAAAAAAAAAAAAAA='
      command_off: 'JgCSACoNKg0OKSkNKg0OKQ8pDikQJw8oDykp4yoNKgwOKSoNKg0RJg8pDSoOKREmECct3ywLKwwQJywKLAsRJhEnESYOKhAmEScp4ywLKQ0RJykNLAgTKA0qDSoOKQ4qDikp4ykOKgkRKSsJLA4NKhAoECcQJxAnECcs4CsOKA4QJywLKwwQJxAnECgQJxAnECcsAA0FAAAAAAAA'
    fan_speed:
      friendly_name: "Speed"
      command_on: 'JgDyACoNKgwPKCoNKg0PKA8pDikPKA8oKQ4P/ioNKg0PKCoNKgwPKQ8oDygPKA8pKQ4O/ioNKg0PKCoMKg0QKA4pDygPKA8oKg0P/yoMKwwPKCoNKg0OKQ8oDygPKA8pKg0P/SoNKg0OKSoMKwwPKQ4pDygPKA8pKQ0P/ioNKg0OKSoMKwoRKQ4pDygPKA8oKwwP/ioNKg0OKCsMKQ4PKA8pDikPKA8oKwwP/ioNKQ4PKCkNKg0PKA8pDikPKA8oKg0P/ioNKgwPKCoNKg0PKA8oDykPKA8oKg0P/yoNKQ0PKCoNKQ4OKQ8pDSkPKQ8oKg0PAA0FAAAAAAAA'
    fan_mode:
      friendly_name: "Swing"
      command_on: 'JgBiACoNKg0OKSoMKwwPKQ8oKgsRKA8oDygP/yoNKgwPKCsMKg0PKA8oKwwPKQ8oDygP/yoMKwwPKCoNKg0PKA8oKg0PKA8oDykP/ykNKg0PKCoNKgsQKQ8oKg0PKA8oDykPAA0FAAAAAAAA'
    fan_timer:
      friendly_name: "Timer"
      command_on: 'JgCSACoNKQ0OKSoNKg0OKQ8oDykpDg8oDikP/iwLKg0NKikNKg0PKA8pDikqDQ8oDygP/ioNKg0NKSoNKg0OKQ8pDikqDQ8oDygP/iwLKg0OKSoMKQ4PKQ4pECcqDQ8oDygR/CoNKg0NKioMKg0OKQ8pDikqDQ8oDygP/yoNKQ0PKCoNKg0PKA8oDygpDg8pDikPAA0FAAAAAAAA'

###########################################################
# command_line
############################################################
- platform: command_line
  switches:    
    tv_plug:
      command_on: !secret tv_plug_on_ifttt
      command_off: !secret tv_plug_off_ifttt
      friendly_name: "TV Plug"
    sonoff_co2:
      command_on: !secret sonoff_co2_on_ifttt
      command_off: !secret sonoff_co2_off_ifttt
      friendly_name: "CO2"
    sonoff_goldie:
      command_on: !secret sonoff_goldie_on_ifttt
      command_off: !secret sonoff_goldie_off_ifttt
      friendly_name: "Goldie"
    sonoff_twenty:
      command_on: !secret sonoff_20_on_ifttt
      command_off: !secret sonoff_20_off_ifttt
      friendly_name: "20"
    sonoff_nano:
      command_on: !secret sonoff_nano_on_ifttt
      command_off: !secret sonoff_nano_off_ifttt
      friendly_name: "Shrimp Nano"
    sonoff_2gallon:
      command_on: !secret sonoff_2gallon_on_ifttt
      command_off: !secret sonoff_2gallon_off_ifttt
      friendly_name: "2 Gallon"
    # #Switch for Foscam Motion Detection
    # foscam_motion:
      # command_on: 'curl -k "https://192.168.1.37:443/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&usr=arunrajappan@gmail.com&pwd=foscam4050"'
      # command_off: 'curl -k "https://192.168.1.37:443/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&usr=arunrajappan@gmail.com&pwd=foscam4050"'
      # command_state: 'curl -k --silent "https://192.168.1.37:443/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=arunrajappan@gmail.com&pwd=foscam4050" | grep -oP "(?<=isEnable>).*?(?=</isEnable>)"'
      # value_template: '{{ value == "1" }}'